### PR TITLE
Update to build 1.00.15

### PR DESCRIPTION
**Pull request by fwaddle**

### CODE REVIEW

**Comment by martinrybak** [comment]
Thanks!

**Comment by martinrybak** [comment]
Hi @fwaddle, any ideas to compile a single binary that can run on both iOS and OS X? See https://github.com/martinrybak/SQLClient/issues/32

**Comment by fwaddle** [comment]
HI @martinrybak, That's strange because it's building a FAT binary with the x86/x86_64 versions compiled in. The new build script should be building the same thing as the previous one did.
I'll subscribe to #32 and follow what's happening and see if I can help once drd27 replies.

**Comment by fwaddle** [comment]
So I did some searching and it appears that warning was added in Xcode 7. It has nothing to do with the update to the latest FreeTDS or SQLClient. I had a look at how other projects sorted it out and they now include a seperate build process for macOS. Here is the best example I've found of a good and clean build script:

https://gist.github.com/dtrotzjr/0410c80faed1033fa312

Perhaps drd27 would be kind enough to modify the current build script...

Hope that helps.

**Comment by martinrybak** [comment]
@fwaddle thanks for the link!

**Pull request merged**
